plugin: aws_ec2
regions:
  - us-west-1

aws_credentials_file: /home/vagrant/TerraformAnsibleFinal/Terraform/aws/credentials

filters:
  instance-state-name: running
  tag:Name: "vfc-*"

hostnames: 
  - tag:Name
  - public-ip-address

keyed_groups:
  - key: tags.role
    prefix: role
compose:
  ansible_host: public_ip_address 
